### ISSUE TITLE
Is com.winterbe.react.React.renderCommentBox thread safe?

### ISSUE THREAD

**Issue by bodrin** [winterbe/spring-react-example#2]
First - thank you for the nice work!

I'm not an expert on nashorn and just wondered whether com.winterbe.react.React.renderCommentBox is thread safe as the script engine instance is shared in this class?

I assume it is just like calling a static method but is this the case?

Thanks!

**Comment by winterbe** [comment]
Thanks for your Feedback. The Nashorn Script Engine itself is thread-safe as long as the evaluated script doesn't share state. So in this example all the self-written JavaScript (`commentBox.js`) is thread-safe. But I'm not entirely sure about the vendor used vendor scripts (`React.js`, `Showdown.js`).

This is something we have to ask the React.js team.

**Comment by bodrin** [comment]
I see. Thanks for the reply.

So in the worst case (if it is not thread-safe) we can use an instance of nashorn (your React class) per http request thread in a thread local for example.
What do you think?

Do you now if someone does server side rendering with nashorn/javascript in production? And with react?

**Comment by winterbe** [comment]
It seems that React isn't thread-safe, see #3 for further infos.
